MiraiAnimation/Pages/Admin/ManageStaff.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;

namespace MiraiAnimation.Pages.Admin {
	[Authorize(Policy = "AdminRole")]
	public class ManageStaffModel : PageModel {
        private readonly IDbService<Staff, string> _staffService;

        public IEnumerable<Staff> Staffs { get; set; }

        [BindProperty]
        public Staff Staff { get; set; }

        public ManageStaffModel(IDbService<Staff, string> staffService) {
            _staffService = staffService;
        }

        public void OnGet() {
            Staffs = _staffService.GetAll();
        }

        public IActionResult OnPostEdit() {
            if(!ModelState.IsValid) {
                Staffs = _staffService.GetAll();
                return Page();
            }

            _staffService.EditElement(Staff);

            return new RedirectToPageResult("/Admin/ManageStaff");
        }

        public IActionResult OnPostAdd() {
            if (!ModelState.IsValid) {
                Staffs = _staffService.GetAll();
                return Page();
            }

            _staffService.AddElement(Staff);

            return new RedirectToPageResult("/Admin/ManageStaff");
        }

        public IActionResult OnPostDelete(string id) {
            _staffService.RemoveElement(_staffService.GetById(id));

            return new RedirectToPageResult("/Admin/ManageStaff");
        }
    }
}

MiraiAnimation/Pages/Animation.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;

namespace MiraiAnimation.Pages {
    public class AnimationModel : PageModel {
		public IEnumerable<Animation> animations;
        private IDbService<Animation, string> _animService;

        public AnimationModel(IDbService<Animation, string> animService) {
            _animService = animService;
        }

		public void OnGet() {
            animations = _animService.GetAll();
        }
    }
}

MiraiAnimation/Pages/AnimationPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.IdGenerators;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace MiraiAnimation.Pages
{
    public class AnimationPageModel : PageModel {
        private IDbService<Animation, string> _animService;
		public Animation Animation { get; set; }

		public AnimationPageModel(IDbService<Animation, string> animService) {
			_animService = animService;
		}
		public void OnGet(string id) {
			Animation = _animService.GetById(id);
		}

		public IActionResult OnPostAddReview(ReviewInputModel input) {

			if(!ModelState.IsValid) {
				Animation = _animService.GetById(input.Id);
				return Page();
			}

			Animation anim = _animService.GetById(input.Id);

			Recensione recensione = new Recensione {
				user = new ObjectId(HttpContext.User.Claims.First(claim => claim.Type == "id").Value),
				username = HttpContext.User.Claims.First(claim => claim.Type == ClaimTypes.Name).Value,
				voto = int.Parse(input.Voto),
				commento = input.Commento,
				_id = (MongoDB.Bson.ObjectId) ObjectIdGenerator.Instance.GenerateId(anim.recensioni, anim)
			};

			anim.recensioni.Add(recensione);

			_animService.EditElement(anim);

			return new RedirectToPageResult("/AnimationPage", new { id = input.Id });
		}


		public class ReviewInputModel {
			[Required]
			public string Id { get; set; }
			[Required]
			[Range(1, 5)]
			public string Voto { get; set; }
			[Required]
			[Length(1, 255)]
			public string Commento { get; set; }
		}
	}
}

MiraiAnimation/Pages/Index.cshtml.cs
using Mailjet.Client;
using Mailjet.Client.TransactionalEmails;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Transactions;

namespace MiraiAnimation.Pages {
    public class IndexModel : PageModel {
        private readonly ILogger<IndexModel> _logger;
        private readonly PasswordHasher<User> _passHasher;
        private readonly IDbService<User, string> _usersCollection;
        private readonly IMailjetClient _mailClient;
        private readonly IConfiguration _configuration;

		public IndexModel(ILogger<IndexModel> logger, PasswordHasher<User> passHasher, IDbService<User, string> usersCollection, IMailjetClient mailClient, IConfiguration configuration) {
            _logger = logger;
            _passHasher = passHasher;
            _usersCollection = usersCollection;
            _mailClient = mailClient;
            _configuration = configuration;
        }

        public void OnGet() {

        }

        public async Task<IActionResult> OnPostLogin([Required] string Username, [Required] string Password) {

			if (!ModelState.IsValid) {
				return Page();
			}

			User user;
            if((user = _usersCollection.GetByProperty(Username)) != null && _passHasher.VerifyHashedPassword(user, user.password, Password) == PasswordVerificationResult.Success) {
                List<Claim> claims = [
                    new Claim("id", user.id.ToString()),
                    new Claim(ClaimTypes.Name, user.username),
                    new Claim("Nome", user.nome),
                    new Claim("Cognome", user.cognome),
                    new Claim("Email", user.email),
                    new Claim("DataNascita", user.dataNascita.ToString("yyyy/MM/dd")),
                    new Claim("Indirizzo", user.indirizzo.ToString()),
                    new Claim("Tipo", user.tipo),
                    new Claim("Verificato", user.verificato.ToString())
                ];

				ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

				await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), new AuthenticationProperties());

                return new RedirectToPageResult("Index");
			}

            return Page();
        }

        public async Task<IActionResult> OnPostSignup(User user) {

            if (!ModelState.IsValid) {
                return Page();
            }

            user.tipo = "utente";
            user.password = _passHasher.HashPassword(user, user.password);
            user.datiVerifica.token = RandomNumberGenerator.GetHexString(16);
            user.datiVerifica.scadenza = DateTime.Now.AddMinutes(10);
            user.verificato = false;

            if (_usersCollection.AddElement(user)) {
                string link = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}/Users/VerifyMail/{user.datiVerifica.token}/{user.id}";

                string mailContent = $"<h2>Verifica e-mail</h2></br>"
                       + $"Clicca sul seguente link per attivare la mail: <a href='{link}'>Verifica mail</a>";
                var mail = new TransactionalEmailBuilder()
                    .WithFrom(new SendContact(_configuration["EMAIL"]))
                    .WithSubject("Verifica e-mail")
                    .WithHtmlPart(mailContent)
                    .WithTo(new SendContact(user.email))
                    .Build();

				await _mailClient.SendTransactionalEmailAsync(mail);
				return new RedirectToPageResult("Index");
            }

            return Page();

        }

        public async Task<IActionResult> OnGetLogout() {
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return new RedirectToPageResult("Index");
		}

        public async Task<IActionResult> OnGetResetPassword() {
            User user = _usersCollection.GetById(User.FindFirst("id").Value);

            if (user == null) {
                return Page();
            }

            user.datiVerifica = new DatiVerifica();
            user.datiVerifica.token = RandomNumberGenerator.GetHexString(16);
            user.datiVerifica.scadenza = DateTime.Now.AddMinutes(10);

            _usersCollection.EditElement(user);

            string link = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}/Users/ResetPassword/{user.datiVerifica.token}/{user.id}";

            string mailContent = $"<h2>Reimposta password</h2></br>"
                   + $"Clicca sul seguente link per reimpostare la password: <a href='{link}'>Reimposta password</a>";
            var mail = new TransactionalEmailBuilder()
                .WithFrom(new SendContact(_configuration["EMAIL"]))
                .WithSubject("Reimposta password")
                .WithHtmlPart(mailContent)
                .WithTo(new SendContact(user.email))
                .Build();

            await _mailClient.SendTransactionalEmailAsync(mail);

            return Page();
        }
    }
}

MiraiAnimation/Pages/ListaStaff.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;

namespace MiraiAnimation.Pages {
    public class ListaStaffModel : PageModel {
        public IEnumerable<Staff> staffs;
        private IDbService<Staff, string> _staffService;

        public ListaStaffModel(IDbService<Staff, string> staffService) {
            _staffService = staffService;
        }

		public void OnGet() {
            staffs = _staffService.GetAll();
        }
    }
}

MiraiAnimation/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MiraiAnimation.Pages {
    public class PrivacyModel : PageModel {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger) {
            _logger = logger;
        }

        public void OnGet() {
        }
    }

}

MiraiAnimation/Pages/Animation.cshtml
@page
@model MiraiAnimation.Pages.AnimationModel

@section CSS{
	<link rel="stylesheet" href="/css/animation.css" type="text/css">
}

<div class="container pt-4 h-auto mt-4 bg-dark">
	<div class="row">
		@foreach (MiraiAnimation.Model.Animation anim in Model.animations) {
			<div class="col-5 mx-auto px-0 mt-5 text-center">
				<a class="animation" asp-page="AnimationPage" asp-route-id="@anim.id">
					<img src="data:image/String;base64,@((anim.immagine != null) ? anim.immagine : " ")" alt="logo animazione" onerror="this.src='/img/anim/noimage.png' "> <br />
					<span>@anim.titolo</span>
				</a>
			</div>
		}
	</div>
</div>

MiraiAnimation/Pages/AnimationPage.cshtml
@page "{id}"
@model MiraiAnimation.Pages.AnimationPageModel
@section CSS {
	<link rel="stylesheet" href="/css/animationPage.css" type="text/css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
}
@{
	@using MiraiAnimation.Model
}
<div id="container" class="container h-auto pt-4 mt-4 bg-dark">
	<div class="row pb-5">
		<div class="col">
			<img src="data:image/String;base64,@((@Model.Animation.immagine != null) ? @Model.Animation.immagine : " ")>" alt="logo animazione" onerror="this.src='/img/anim/noimage.png' ">
		</div>
		<div class="col">
			<p id="nome">@Model.Animation.titolo</p>

			<p>
				<b>Tipo:</b> @Model.Animation.tipo<br />
				<b>Uscita:</b> @Model.Animation.dataUscita <br />

				<b>Genere:</b> @Model.Animation.genere
			</p>

			<p>
				<b>Staff:</b><br />
				@while (false) {
					<span></span> <br />
				}
		</div>
	</div>
	<div id="rec" class="row">
		<div class="col">
			<span id="insertrec">Inserisci una recensione</span> <br />
			@if (User.Claims.Count() > 0) {
				<span>Voto</span>
				<ul id="star">
					<li class="fa fa-star fa-2x" id="1star" onclick="checkStar(this.id)"></li>
					<li class="fa fa-star fa-2x" id="2star" onclick="checkStar(this.id)"></li>
					<li class="fa fa-star fa-2x" id="3star" onclick="checkStar(this.id)"></li>
					<li class="fa fa-star fa-2x" id="4star" onclick="checkStar(this.id)"></li>
					<li class="fa fa-star fa-2x" id="5star" onclick="checkStar(this.id)"></li>
				</ul>
				<form name="reviewForm" asp-page-handler="AddReview">
					<input type="hidden" name="Id" value="@Model.Animation.id">
					<input type="hidden" name="Voto" id="voto">
					<span id="comment">Commento</span> <br />
					<textarea name="Commento" maxlength="255" rows="4" cols="30"></textarea><br /> <br />
					<input type="submit" value="Inserisci"> <br />
					<div asp-validation-summary="All"></div>
				</form>
				<span class="error" id="errorComment"></span><br />
			} else {
			<p> Devi essere registrato per scrivere una recensione </p>
			}

			<span id="recensioni">Recensioni</span><br/>
			@if(Model.Animation.recensioni == null || Model.Animation.recensioni.Count == 0) {
				<p>Nessuna recensione disponibile</p>
			} else {
				@foreach (Recensione recensione in Model.Animation.recensioni) {
					<p>
						Utente: @recensione.username<br/>
						Voto: @recensione.voto<br />
						Commento:<br />
						<span>
							@recensione.commento
						</span>
					</p>
				}
			}


		</div>
	</div>
</div>

@section Scripts {
	<script src="/js/animationPage.js"></script>
}

MiraiAnimation/Pages/Index.cshtml
@page
@model IndexModel
@section CSS{
	<link rel="stylesheet" href="css/index.css" type="text/css">
}
@{
    ViewData["Title"] = "Home page";
}

<div class="parallax">
	<img class="mx-auto d-block w-100 h-auto" src="img/bgText.png" alt="backgroundParallax">
</div>

<div class="container mx-6 bg-dark h-auto">
	<div>
		<img class="mx-auto d-block animation" src="img/logo.png" alt="logo">
		<img class="mx-auto mt-5 d-block w-100 h-auto" src="img/descrizione.png" alt="descrizione">
	</div>
</div>


<!--  form che serve solo per mantenere valori per lo script JS insertError() -->
<form>
	<input type="hidden" id="errorType" name="errorType" value="<%= errorType %>">
	<input type="hidden" id="error" name="error" value="<%= errorString %>">
</form>


@section Scripts{
	<script src="js/index.js"></script>
	<script>
		$(document).ready(function () {
			$(".animation").hover(function () {
				$(".animation").animate({ width: '40%' });
			}, function () {
				$(".animation").animate({ width: '30%' });
			});
		});
	</script>
}

MiraiAnimation/Pages/ListaStaff.cshtml
@page
@model MiraiAnimation.Pages.ListaStaffModel
@section CSS{
    <link rel="stylesheet" href="css/listaStaff.css" type="text/css">
}
@using MiraiAnimation.Model;

<div id="containerStaff" class="container pt-4 h-auto mt-4 bg-dark">
	<div class="row">
		@{int id = 1;}
		@foreach (Staff staff in Model.staffs) {
			<div class="col-6 text-center">
				<a data-toggle="collapse" href="@(" #" + id)" role="button" aria-expanded="false" aria-controls="<%= id %>">
					<img src="img/staff.png" class="w-50" alt="staff"><br/>
					<span>@(staff.nome + " " + staff.cognome)</span>
				</a><br />
				<div class="collapse" id="@id">
					<b>Anni di Servizio:</b> @staff.anniServizio<br/>
					<b>Ruolo:</b> @staff.ruolo

					<p>
						<span>Animazioni</span> <br/>

						<a href=""></a>
						<br/>
					</p>
				</div>
			</div>
			id++;
		} 
	</div>
</div>

MiraiAnimation/Pages/Shop.cshtml
@page
@model MiraiAnimation.Pages.ShopModel
@section CSS{
	<link rel="stylesheet" href="css/shop.css" type="text/css">
}
@using MiraiAnimation.Model;

<div id="container" class="container pt-4 mt-4 bg-dark">
	@foreach(BluRay bd in Model.bds) {
		<div class="row pb-5">
			<img class="float-left" src="data:image/String;base64,@((bd.immagine != null) ? bd.immagine : " ")" alt="cofanetto" onerror="this.src='img/bd/noimage.png'"/>

			<div class="descrizione mr-4">
				<p class="testo">
					<a class="link" href="">@bd.anim.titolo</a> <br />
					<span class="prezzo">Prezzo:</span> @bd.prezzo
					<span></span><br />
					<span class="contenuto">Descrizione:</span> <br />
					<span>@bd.descrizione</span>
				</p>

				@if(User.Claims.Count() > 0) {
					<form name="shopForm" asp-page-handler="Add" onsubmit="return checkForm(this)">
						<input type="hidden" asp-for="Input.Id" value="@bd.id">
						<input type="hidden" asp-for="Input.Prezzo" value="@bd.prezzo">
						<label asp-for="Input.Quantità"> Quantità </label>
						<input type="number" asp-for="Input.Quantità" min="1">
						<br />
						<span class="error" asp-validation-for="Input.Quantità"></span>
						<input type="submit" value="Acquista" class="submit">
					</form>
					<span class="error" id=""></span>
					<p>  </p>

				} else {
					<p> Devi essere registrato per poter effettuare l'acquisto</p>
				} 
			</div>
		</div>
	}
</div>

@section Scripts{
	<script src="js/shop.js"></script>
}