MiraiAnimation/Pages/Index.cshtml.cs
using Mailjet.Client;
using Mailjet.Client.TransactionalEmails;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Transactions;

namespace MiraiAnimation.Pages {
    public class IndexModel : PageModel {
        private readonly ILogger<IndexModel> _logger;
        private readonly PasswordHasher<User> _passHasher;
        private readonly IDbService<User, string> _usersCollection;
        private readonly IMailjetClient _mailClient;
        private readonly IConfiguration _configuration;

		public IndexModel(ILogger<IndexModel> logger, PasswordHasher<User> passHasher, IDbService<User, string> usersCollection, IMailjetClient mailClient, IConfiguration configuration) {
            _logger = logger;
            _passHasher = passHasher;
            _usersCollection = usersCollection;
            _mailClient = mailClient;
            _configuration = configuration;
        }

        public void OnGet() {

        }

        public async Task<IActionResult> OnPostLogin([Required] string Username, [Required] string Password) {

			if (!ModelState.IsValid) {
				return Page();
			}

			User user;
            if((user = _usersCollection.GetByProperty(Username)) != null && _passHasher.VerifyHashedPassword(user, user.password, Password) == PasswordVerificationResult.Success) {
                List<Claim> claims = [
                    new Claim("id", user.id.ToString()),
                    new Claim(ClaimTypes.Name, user.username),
                    new Claim("Nome", user.nome),
                    new Claim("Cognome", user.cognome),
                    new Claim("Email", user.email),
                    new Claim("DataNascita", user.dataNascita.ToString("yyyy/MM/dd")),
                    new Claim("Indirizzo", user.indirizzo.ToString()),
                    new Claim("Tipo", user.tipo),
                    new Claim("Verificato", user.verificato.ToString())
                ];

				ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

				await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), new AuthenticationProperties());

                return new RedirectToPageResult("Index");
			}

            return Page();
        }

        public async Task<IActionResult> OnPostSignup(User user) {

            if (!ModelState.IsValid) {
                return Page();
            }

            user.tipo = "utente";
            user.password = _passHasher.HashPassword(user, user.password);
            user.datiVerifica.token = RandomNumberGenerator.GetHexString(16);
            user.datiVerifica.scadenza = DateTime.Now.AddMinutes(10);
            user.verificato = false;

            if (_usersCollection.AddElement(user)) {
                string link = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}/Users/VerifyMail/{user.datiVerifica.token}/{user.id}";

                string mailContent = $"<h2>Verifica e-mail</h2></br>"
                       + $"Clicca sul seguente link per attivare la mail: <a href='{link}'>Verifica mail</a>";
                var mail = new TransactionalEmailBuilder()
                    .WithFrom(new SendContact(_configuration["EMAIL"]))
                    .WithSubject("Verifica e-mail")
                    .WithHtmlPart(mailContent)
                    .WithTo(new SendContact(user.email))
                    .Build();

				await _mailClient.SendTransactionalEmailAsync(mail);
				return new RedirectToPageResult("Index");
            }

            return Page();

        }

        public async Task<IActionResult> OnGetLogout() {
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return new RedirectToPageResult("Index");
		}

        public async Task<IActionResult> OnGetResetPassword() {
            User user = _usersCollection.GetById(User.FindFirst("id").Value);

            if (user == null) {
                return Page();
            }

            user.datiVerifica = new DatiVerifica();
            user.datiVerifica.token = RandomNumberGenerator.GetHexString(16);
            user.datiVerifica.scadenza = DateTime.Now.AddMinutes(10);

            _usersCollection.EditElement(user);

            string link = $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}/Users/ResetPassword/{user.datiVerifica.token}/{user.id}";

            string mailContent = $"<h2>Reimposta password</h2></br>"
                   + $"Clicca sul seguente link per reimpostare la password: <a href='{link}'>Reimposta password</a>";
            var mail = new TransactionalEmailBuilder()
                .WithFrom(new SendContact(_configuration["EMAIL"]))
                .WithSubject("Reimposta password")
                .WithHtmlPart(mailContent)
                .WithTo(new SendContact(user.email))
                .Build();

            await _mailClient.SendTransactionalEmailAsync(mail);

            return Page();
        }
    }
}

MiraiAnimation/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiraiAnimation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiraiAnimation.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="/css/navbar.css" type="text/css" asp-append-version="true"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	@await RenderSectionAsync("CSS", required: false)
</head>
<body>
    <header>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="navbar-brand">
				<span id="eng">Mirai Animation</span>
				<span id="jap" lang="ja">未来 アニメーション</span>
			</div>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item mx-auto">
						<a class="nav-link" asp-page="/Index">Home</a>
					</li>
					<li class="nav-item mx-auto">
						<a class="nav-link" asp-page="/Animation">Animazioni</a>
					</li>
					<li class="nav-item mx-auto">
						<a class="nav-link" asp-page="/ListaStaff">Personale</a>
					</li>
					<li class="nav-item mx-auto">
						<a class="nav-link" asp-page="/Shop">Negozio</a>
					</li>
				</ul>

				<ul class="navbar-nav ml-auto text-center">
					@if (User.Claims.Count() == 0) {	
						<li class="nav-item dropdown align-middle">
							<a class="nav-link dropdown-toggle" href="#" id="logDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Accedi
							</a>
							<div class="dropdown-menu py-2 px-3 dropdown-menu-right" id="dropdownLog" aria-labelledby="logDropdown">
								<form name="logForm" class="px-auto ml-auto text-center" asp-page="Index" asp-page-handler="Login" onsubmit="return checkLogForm()">
									<div class="form-group">
										<label for="userLog">Username</label>
										<input type="text" id="userLog" name="Username" placeholder="Username" required> <br />
										<span class="error" id="errorLogUser"></span>
									</div>
									<div class="form-group">
										<label for="passLog">Password</label>
										<input type="password" id="passLog" name="Password" placeholder="Password" required> <br />
										<span class="error" id="errorLogPass"></span>
									</div>
									<input type="submit" value="Entra"> <br />
									<div asp-validation-summary="All"></div>
								</form>
								<span id="errorLog"></span><br />

							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#" data-toggle="modal" data-target="#signUpModal">Registrati</a>
						</li>
					}
					else
					{
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Sezione Utente
							</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
								<a class="dropdown-item" asp-page="/Users/Cart">Carrello</a>
								<a class="dropdown-item" asp-page="/Users/Orders">Ordini effettuati</a>
								<!--  <div class="dropdown-divider"></div>-->
								<a class="dropdown-item" asp-page="/Users/Account">Account</a>
								<a class="dropdown-item" data-toggle="modal" data-target="#resetModal">Reimposta password</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" asp-page="/Index" asp-page-handler="Logout">Log out</a>
							</div>
						</li>
					
						@if (User.FindFirst("tipo").Value == "admin") { <!-- da modificare in futuro-->
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="adminDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Sezione Admin
								</a>
								<div class="dropdown-menu dropdown-menu-right" aria-labelledby="adminDropdown">
									<a class="dropdown-item" asp-page="/Admin/ManageAnimation">Pannello Animazioni</a>
									<a class="dropdown-item" asp-page="/Admin/ManageStaff">Pannello Personale</a>
									<!--  <div class="dropdown-divider"></div>-->
									<a class="dropdown-item" asp-page="/Admin/ManageBluRay">Pannello Blu-ray</a>
									<a class="dropdown-item" asp-page="/Admin/ManageUser">Pannello Utenti</a>
								</div>
							</li>
						} 
					}
				</ul>

			</div>
		</nav>

		<!-- form registrazione-->
		<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="signUpLabel" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered" role="document">
				<div class="modal-content bg-opacity color">
					<div class="modal-header">
						<h5 class="modal-title" id="signUpLabel">Registrati</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<form name="signForm" asp-page="/Index" asp-page-handler="Signup" onsubmit="return checkSignForm()">
						<div class="modal-body mt-3">
							<div class="form-group">
								<input name="email" required>
								<label for="user">E-mail</label><br />
								<span class="error" id="errorSignEmail"></span>
							</div>
							<div class="form-group">
								<input type="text" id="user" name="username" required>
								<label for="user">Username</label><br />
								<span class="error" id="errorSignUser"></span>
							</div>
							<div class="form-group">
								<input type="password" id="password" name="password" required>
								<label for="password">Password</label><br />
								<span class="error" id="errorSignPass"></span>
							</div>
							<div class="form-group">
								<input type="text" id="name" name="nome" required>
								<label for="name">Nome</label><br />
								<span class="error" id="errorSignName"></span>
							</div>
							<div class="form-group">
								<input type="text" id="surname" name="cognome" required>
								<label for="surname">Cognome</label><br />
								<span class="error" id="errorSignSurname"></span>
							</div>
							<div class="form-group">
								<input type="text" id="birthDate" name="dataNascita" required>
								<label for="birthDate">Data di Nascita</label><br />
								<span class="error" id="errorSignBirth"></span>
							</div>
							<div class="form-group">
								<h6 style="margin-bottom: 15px">Indirizzo</h6>
								<input type="text" id="city" name="indirizzo.città" required>
								<label for="city">Città</label><br />
								<input type="text" id="via" name="indirizzo.via" required>
								<label for="via">Via</label><br />
								<input type="text" id="cap" name="indirizzo.CAP" required>
								<label for="cap">CAP</label><br />
								<span class="error" id="errorSignAddress"></span>
							</div>
							<span id="errorSign"></span><br />
							<div asp-validation-summary="All"></div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
							<input type="submit" value="Registrati" class="btn btn-secondary">
						</div>
					</form>
				</div>
			</div>
		</div>

		@if(User.Claims.Count() > 0 && bool.Parse(User.FindFirst("Verificato").Value) == false) {
			<div>
				<span>Account non verificato. Visiona la tua casella mail</span>
			</div>
		}

		<!-- modal reset password-->
		<div class="modal fade" id="resetModal" tabindex="-1" role="dialog" aria-labelledby="resetModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-sm" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="resetModalLabel">Reimposta password</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						Sicuro di voler reimpostare la password?
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
						<a asp-page="/Index" asp-page-handler="ResetPassword" class="btn btn-primary">Si</a>
					</div>
				</div>
			</div>
		</div>
    </header>

            @RenderBody()

		<footer class="border-top footer text-muted">
			<div class="container">
				&copy; 2024 - MiraiAnimation - <a asp-area="" asp-page="/Privacy">Privacy</a>
			</div>
		</footer>




	<!--<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	-->
    <script src="~/js/site.js" asp-append-version="true"></script>
	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.5.1.js" type="text/javascript"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="/js/navbar.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>