MiraiAnimation/Pages/Admin/ManageUser.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;

namespace MiraiAnimation.Pages.Admin {
	[Authorize(Policy = "AdminRole")]
	public class ManageUserModel : PageModel {
        private readonly IDbService<User, string> _userCollection;

        public IEnumerable<User> Users { get; set; }

        [BindProperty]
        public User User { get; set; }
        public ManageUserModel(IDbService<User, string> userCollection) {
			_userCollection = userCollection;
        }

        public void OnGet() {
            Users = _userCollection.GetAll();
        }

        public IActionResult OnPostEdit() {
            if (!ModelState.IsValid) {
                Users = _userCollection.GetAll();
                return Page();
            }

            User _user = _userCollection.GetById(User.id.ToString());

            if(User.password != null) {
				PasswordHasher<User> hasher = new PasswordHasher<User>();

                User.password = hasher.HashPassword(User, User.password);
			} else {
                User.password = _user.password;

			}

            User.indirizzo.id = _user.indirizzo.id;
            User.verificato = _user.verificato;
            User.carrello = _user.carrello;
            User.ordini = _user.ordini;
            User.datiVerifica = _user.datiVerifica;

            _userCollection.EditElement(User);

            return new RedirectToPageResult("/Admin/ManageUser");
        }

        public IActionResult OnPostDelete(string id) {
            _userCollection.RemoveElement(_userCollection.GetById(id.ToString()));

			return new RedirectToPageResult("/Admin/ManageUser");
		}
    }
}

MiraiAnimation/Pages/Users/Account.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.IdGenerators;
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;

namespace MiraiAnimation.Pages.Users {
    [Authorize]
    public class AccountModel : PageModel {
        private readonly IDbService<User, string> _userCollection;
        [BindProperty]
        public AccountInputModel user { get; set; }

        public AccountModel(IDbService<User, string> userCollection) {
            _userCollection = userCollection;
        }

        public void OnGet() {

        }

        public async Task<IActionResult> OnPost() {
            if (!ModelState.IsValid) {
                return Page();
            }

			User userToReplace = _userCollection.GetById(User.FindFirst("id").Value);
            userToReplace.nome = user.nome;
			userToReplace.cognome = user.cognome;
            userToReplace.dataNascita = user.dataNascita;
            userToReplace.indirizzo = user.indirizzo;
            userToReplace.indirizzo.id = (ObjectId) ObjectIdGenerator.Instance.GenerateId(userToReplace, userToReplace.indirizzo);

			_userCollection.EditElement(userToReplace);

            //updating the current ClaimsPrincipal with the new data
            var userIdentity = User.Identity as ClaimsIdentity;

            userIdentity.RemoveClaim(userIdentity.FindFirst("Nome"));
			userIdentity.RemoveClaim(userIdentity.FindFirst("Cognome"));
			userIdentity.RemoveClaim(userIdentity.FindFirst("DataNascita"));
			userIdentity.RemoveClaim(userIdentity.FindFirst("Indirizzo"));

            userIdentity.AddClaim(new Claim("Nome", userToReplace.nome));
			userIdentity.AddClaim(new Claim("Cognome", userToReplace.cognome));
			userIdentity.AddClaim(new Claim("DataNascita", userToReplace.dataNascita.ToString("yyyy/MM/dd")));
			userIdentity.AddClaim(new Claim("Indirizzo", userToReplace.indirizzo.ToString()));

			await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(userIdentity), new AuthenticationProperties());

			return Page();
        }
    }

    public class AccountInputModel {
		[Required]
		[MaxLength(20)]
		public string nome { get; set; }
		[Required]
		[MaxLength(20)]
		public string cognome { get; set; }
		[Required]
		[DataType(DataType.Date)]
		public DateTime dataNascita { get; set; }
		[Required]
		public Indirizzo indirizzo { get; set; }
	}
}

MiraiAnimation/Pages/Users/OrderSuccess.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;
using MongoDB.Bson.Serialization.IdGenerators;

namespace MiraiAnimation.Pages.Users {
    [Authorize]
    public class OrderSuccessModel : PageModel {
        private readonly IDbService<User, string> _userService;

        public OrderSuccessModel(IDbService<User, string> userService) {
            _userService = userService;
        }
        public void OnGet() {
            User user = _userService.GetById(User.FindFirst("id").Value);

            user.ordini.Add(new OrderElement {
				Id = (MongoDB.Bson.ObjectId) ObjectIdGenerator.Instance.GenerateId(user.ordini, user),
				prodotti = user.carrello,
                dataAcquisto = DateTime.Now
            });

            user.carrello = new List<CartElement>();

            _userService.EditElement(user);
		}
    }
}

MiraiAnimation/Pages/Users/ResetPassword.cshtml.cs
using Mailjet.Client;
using Mailjet.Client.TransactionalEmails;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;
using System.Security.Cryptography;

namespace MiraiAnimation.Pages.Users {
    public class ResetPasswordModel : PageModel{
        private readonly PasswordHasher<User> _passwordHasher;
        private readonly IMailjetClient _mailClient;
        private readonly IConfiguration _configuration;
        private readonly IDbService<User, string> _userService;

        public string Id { get; set; }
        public bool Succeeded { get; set; } = false;

        public ResetPasswordModel(IMailjetClient mailClient, IConfiguration configuration, IDbService<User, string> userService, PasswordHasher<User> passwordHasher) { 
            _mailClient = mailClient;
            _configuration = configuration;
            _userService = userService;
            _passwordHasher = passwordHasher;
        }
        public IActionResult OnGet(string token, string id) {
            User user = _userService.GetById(id);

            if(user == null || (!token.Equals(user.datiVerifica.token) || user.datiVerifica.scadenza > DateTime.Now)) {
                return BadRequest();
            }

            Id = user.id.ToString();

            return Page();
        }

        public void OnPostReset(string id, string oldPassword, string newPassword, string newPassword2) {
            User user = _userService.GetById(id);

            if(_passwordHasher.VerifyHashedPassword(user, user.password, oldPassword) == PasswordVerificationResult.Success) {
                if(newPassword == newPassword2) {
                    user.password = _passwordHasher.HashPassword(user, newPassword);
                    user.datiVerifica = null;
                    _userService.EditElement(user);
                    Succeeded = true;

                    return;
                }
            }
        }
    }
}

MiraiAnimation/Pages/Users/VerifyMail.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;
using System.Security.Claims;
using System.Security.Cryptography;

namespace MiraiAnimation.Pages.Users {
    public class VerifyMailModel : PageModel {
		private readonly IDbService<User, string> _usersCollection;

        public bool Success { get; set; } = false;
		public bool AlreadyVerified { get; set; } = false;
		public VerifyMailModel(IDbService<User, string> usersCollection) {
            _usersCollection = usersCollection;
        }
        public async void OnGet(string token, string id) {
            User user = _usersCollection.GetById(id);

            if (user.verificato) {
                AlreadyVerified = true;
                return;
            }

            if(token.Equals(user.datiVerifica.token) && user.datiVerifica.scadenza < DateTime.Now) {
                Success = true;
                user.verificato = true;
                user.datiVerifica = null;
                _usersCollection.EditElement(user);

                if(User.Claims.Count() > 0) {
					((ClaimsIdentity)User.Identity).RemoveClaim(User.FindFirst("Verificato"));
					((ClaimsIdentity)User.Identity).AddClaim(new Claim("Verificato", user.verificato.ToString()));

					await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, User, new AuthenticationProperties());
				}
			}
        }
    }
}

MiraiAnimation/Pages/Users/Account.cshtml
@page
@model MiraiAnimation.Pages.Users.AccountModel
@section CSS{
	<link rel="stylesheet" href="/css/account.css" type="text/css">
}

@{
	string[] indirizzo = @User.FindFirst("Indirizzo").Value.Split(' ');
}

<div id="container" class="container h-100 pt-4 mt-4 bg-dark">
	<form id="form" name="formUser" asp-page="Users/Account" onsubmit="return checkForm()">
		<label asp-for="user.nome">Nome:</label><br />
		<input id="nome" type="text" asp-for="user.nome" value="@User.FindFirst("Nome").Value" required> <br />
		<span asp-validation-for="user.nome" class="error" id="errorName"></span><br />

		<label asp-for="user.cognome">Cognome:</label><br />
		<input type="text" id="cognome" asp-for="user.cognome" value="@User.FindFirst("Cognome").Value" required> <br />
		<span class="error" id="errorSurname" asp-validation-for="user.cognome"></span><br />

		<h5>Indirizzo:</h5>
		<label asp-for="user.indirizzo.via">Via:</label><br />
		<input type="text" id="indirizzo" asp-for="user.indirizzo.via" value="@indirizzo[0].Substring(0, indirizzo[0].Length - 1)" required> <br />
		<span class="error" id="errorAddress" asp-validation-for="user.indirizzo.via"></span><br />
		<label asp-for="user.indirizzo.città">Città:</label><br />
		<input type="text" id="indirizzo" asp-for="user.indirizzo.città" value="@indirizzo[1].Substring(0, indirizzo[1].Length - 1)" required> <br />
		<span class="error" id="errorAddress" asp-validation-for="user.indirizzo.città"></span><br />
		<label asp-for="user.indirizzo.CAP">CAP:</label><br />
		<input type="text" id="indirizzo" asp-for="user.indirizzo.CAP" value="@indirizzo[2]" required> <br />
		<span class="error" id="errorAddress" asp-validation-for="user.indirizzo.CAP"></span><br />

		<label asp-for="user.dataNascita">Data di Nascita:</label><br />
		<input type="text" id="dataNascita" asp-for="user.dataNascita" value="@User.FindFirst("DataNascita").Value" required> <br /><br />
		<span class="error" id="errorBirthDate" asp-validation-for="user.dataNascita"></span><br />

		<input type="submit"> <input type="reset"> <br /><br />

	</form>

</div>

@section Scripts {
	<script src="/js/account.js"></script>
}

MiraiAnimation/Pages/Users/Cart.cshtml
@page
@model MiraiAnimation.Pages.Users.CartModel
@section CSS{
	<link rel="stylesheet" href="/css/cart.css" type="text/css">
}
@using MiraiAnimation.Model;
@{
	int totale = 0;
}
<div id="container" class="container h-auto pt-4 mt-4 bg-dark">
	<span id="titolo">Carrello</span> <br />

	<div class="row">
		@if (Model.Carrello.Count() == 0){
			<span class="void"> Il carrello è vuoto</span>
		} else { 
			@foreach (CartElement el in Model.Carrello) {
					totale += el.prezzo * el.quantità;


				<div class="col-7 pb-3">
					<img class="float-left" src="data:image/String;base64,@((el.bluRay.immagine != null) ? el.bluRay.immagine : " ")" alt="cofanetto" onerror="this.src='/img/bd/noimage.png'" />

					<div class="descrizione">
						<p>
							Nome: @el.bluRay.anim.titolo<br />
							Descrizione: @el.bluRay.descrizione <br />
							Prezzo: @el.prezzo <br />
							Quantità: @el.quantità<br />
						</p>
					</div>
					<form asp-page="Cart" asp-page-handler="Delete">
						<input type="hidden" name="id" value="@el.Id">
						<input type="submit" value="Elimina">
					</form>
				</div>
			}
		}
	</div>
	<div class="float-right">
		<div class="card card-totale bg-dark">
			<div class="card-body">
				<h5 class="card-title pb-0">Totale:</h5>
				<p class="card-text"> @totale &euro;</p>
				<a asp-page="Cart" asp-page-handler="Checkout" class="btn btn-success">Compra</a>
			</div>
		</div>
	</div>

</div>

MiraiAnimation/Pages/Users/OrderSuccess.cshtml
@page
@model MiraiAnimation.Pages.Users.OrderSuccessModel
@section CSS {
	<link rel="stylesheet" href="/css/successOrder.css" type="text/css">
}

<div id="container" class="container h-auto pt-4 mt-4 bg-dark">
	<span id="titolo">Ordine effettuato con successo</span> <br />

	<div class="row">
		<p style="display: inline-block; text-align: center">Per qualsiasi informazione contattaci via mail.</p>
	</div>
</div>

MiraiAnimation/Pages/Users/Orders.cshtml
@page
@model MiraiAnimation.Pages.Users.OrdersModel
@section CSS{
	<link rel="stylesheet" href="/css/orders.css" type="text/css">
}

@using MiraiAnimation.Model;

<div id="container" class="container pt-4 mt-4 bg-dark h-100">
	<span id="titolo">Ordini effettuati</span>
	<div id="accordion">
		@foreach (OrderElement order in Model.Orders) {
			<div class="card">
				<div class="card-header" id="@("heading" + order.Id)">
					<h5 class="mb-0">
						<button class="btn btn-link" data-toggle="collapse" data-target="#@order.Id" aria-expanded="false" aria-controls="@order.Id">
							Ordine numero @order.Id
						</button>
						<span class="float-right">Effettuato in data @order.dataAcquisto</span>
					</h5>
				</div>

				<div id="@order.Id" class="collapse" aria-labelledby="@("heading" + order.Id)" data-parent="#accordion">
					<div class="card-body">
						<div class="row">
							@foreach (CartElement el in order.prodotti) {
								<div class="col">
									<span>Nome:</span> @el.bluRay.anim.titolo<br />
									<span>Quantità:</span> @el.quantità<br />
									<span>Prezzo:</span> @el.prezzo<br />
								</div>
							}
						</div>
						<a asp-page="/Users/Orders" asp-page-handler="Invoice" asp-route-id="@order.Id">Fattura</a>
					</div>
				</div>
			</div>
		}
	</div>
</div>

MiraiAnimation/Pages/Users/ResetPassword.cshtml
@page "{token?}/{id?}"
@model MiraiAnimation.Pages.Users.ResetPasswordModel
@section CSS{
    <link rel="stylesheet" href="/css/resetPassword.css" type="text/css">
}

<div id="container" class="container pt-4 mt-4 bg-dark pb-2">
    <div class="row d-flex align-items-center justify-content-center">
        @if (Model.Succeeded) {
        <p>Password modificata con successo</p>
        } else {
            <form asp-page-handler="Reset">
                <input type="hidden" name="id" value="@Model.Id">
                <label for="oldPassword">Vecchia password:</label>
                <input type="password" name="oldPassword"><br />
                <label for="newPassword">Nuova password:</label>
                <input type="password" name="newPassword"><br />
                <label for="newPassword2">Ripeti nuova password:</label>
                <input type="password" name="newPassword2"><br />
                <input type="submit">
            </form>
            <p></p>
        }
    </div>
</div>

MiraiAnimation/Pages/Users/VerifyMail.cshtml
@page "{token}/{id}"
@model MiraiAnimation.Pages.Users.VerifyMailModel

@section CSS {
    <style>
        html, body{
	        font-size: 110%;
	        background: #37474F;
	        height: 100%;
	        color: #EEEEEE;
        }
    </style>
}
<div id="container" class="container h-auto pt-4 mt-4 bg-dark">
    @if(Model.Success){
        <h1>Email verificata con successo</h1>
    }

    @if(Model.AlreadyVerified){
        <h1>Email già verificata</h1>
    }
</div>