MiraiAnimation/Pages/Admin/ManageAnimation.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;

namespace MiraiAnimation.Pages.Admin {
	[Authorize(Policy = "AdminRole")]
    public class ManageAnimationModel : PageModel {
        private readonly IDbService<Animation, string> _animCollection;
		private readonly IDbService<Staff, string> _staffCollection;

		public IEnumerable<Animation> Animations { get; set; }
		public IEnumerable<Staff> Staffs { get; set; }
		[BindProperty]
		public Animation Anim {  get; set; }

		public ManageAnimationModel(IDbService<Animation, string> animCollection, IDbService<Staff, string> staffCollection) {
            _animCollection = animCollection;
            _staffCollection = staffCollection;
        }

        public void OnGet() {
            Animations = _animCollection.GetAll();
            Staffs = _staffCollection.GetAll();
        }

        public async Task<IActionResult> OnPostEdit(IFormFile immagine) {
			if(!ModelState.IsValid) {
				Animations = _animCollection.GetAll();
				Staffs = _staffCollection.GetAll();
				return Page();
			}

			Animation animation = _animCollection.GetById(Anim.id.ToString());
            if (immagine != null) {
                using(MemoryStream memoryStream =  new MemoryStream()) {
                    await immagine.CopyToAsync(memoryStream);
					Anim.immagine = memoryStream.ToArray();
				}
			} else {
				Anim.immagine = animation.immagine;
			}

            _animCollection.EditElement(Anim);
            return new RedirectToPageResult("/Admin/ManageAnimation");

        }

		public async Task<IActionResult> OnPostAdd(IFormFile immagine) {
			if (!ModelState.IsValid) {
				Animations = _animCollection.GetAll();
				Staffs = _staffCollection.GetAll();
				return Page();
			}

			if (immagine != null) {
				using (MemoryStream memoryStream = new MemoryStream()) {
					await immagine.CopyToAsync(memoryStream);
					Anim.immagine = memoryStream.ToArray();
				}
			}

			_animCollection.AddElement(Anim);
			return new RedirectToPageResult("/Admin/ManageAnimation");

		}

		public IActionResult OnPostDelete(string id) {
			_animCollection.RemoveElement(_animCollection.GetById(id));
			return new RedirectToPageResult("/Admin/ManageAnimation");

		}
	}
}

MiraiAnimation/Pages/Admin/ManageBluRay.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;

namespace MiraiAnimation.Pages.Admin {
	[Authorize(Policy = "AdminRole")]
	public class ManageBluRayModel : PageModel {
        private readonly IDbService<BluRay, string> _bdService;
        private readonly IDbService<Animation, string> _animService;

        public IEnumerable<BluRay> Bds { get; set; }
        public IEnumerable<Animation> Animations { get; set; }
        [BindProperty]
        public BluRay Bd {  get; set; }

		public ManageBluRayModel(IDbService<BluRay, string> bdService, IDbService<Animation, string> animService) {
            _bdService = bdService;
            _animService = animService;
        }
        public void OnGet() {
            Bds = _bdService.GetAll();
            Animations = _animService.GetAll();
        }

        public async Task<IActionResult> OnPostEdit(IFormFile immagine) {
            if (!ModelState.IsValid) {
				Bds = _bdService.GetAll();
				Animations = _animService.GetAll();
				return Page();
            }

            BluRay _bd = _bdService.GetById(Bd.id.ToString());

            _bd.anim = null;
            _bd.prezzo = Bd.prezzo;
            _bd.descrizione = Bd.descrizione;

            if(immagine != null) {
                using (MemoryStream ms = new MemoryStream()) {
                    await immagine.CopyToAsync(ms);
                    _bd.immagine = ms.ToArray();
                }
            }

            _bdService.EditElement(_bd);

            return new RedirectToPageResult("/Admin/ManageBluRay");
        }

        public async Task<IActionResult> OnPostAdd(IFormFile immagine) {
			if (!ModelState.IsValid) {
				Bds = _bdService.GetAll();
				Animations = _animService.GetAll();
				return Page();
			}

			if (immagine != null) {
                using (MemoryStream ms = new MemoryStream()) {
                    await immagine.CopyToAsync(ms);
                    Bd.immagine = ms.ToArray();
                }
            }

            _bdService.AddElement(Bd);

            return new RedirectToPageResult("/Admin/ManageBluRay");
        }

        public IActionResult OnPostDelete(string id) {
            _bdService.RemoveElement(_bdService.GetById(id));

            return new RedirectToPageResult("/Admin/ManageBluRay");
        }
    }
}

MiraiAnimation/Pages/Admin/ManageStaff.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;

namespace MiraiAnimation.Pages.Admin {
	[Authorize(Policy = "AdminRole")]
	public class ManageStaffModel : PageModel {
        private readonly IDbService<Staff, string> _staffService;

        public IEnumerable<Staff> Staffs { get; set; }

        [BindProperty]
        public Staff Staff { get; set; }

        public ManageStaffModel(IDbService<Staff, string> staffService) {
            _staffService = staffService;
        }

        public void OnGet() {
            Staffs = _staffService.GetAll();
        }

        public IActionResult OnPostEdit() {
            if(!ModelState.IsValid) {
                Staffs = _staffService.GetAll();
                return Page();
            }

            _staffService.EditElement(Staff);

            return new RedirectToPageResult("/Admin/ManageStaff");
        }

        public IActionResult OnPostAdd() {
            if (!ModelState.IsValid) {
                Staffs = _staffService.GetAll();
                return Page();
            }

            _staffService.AddElement(Staff);

            return new RedirectToPageResult("/Admin/ManageStaff");
        }

        public IActionResult OnPostDelete(string id) {
            _staffService.RemoveElement(_staffService.GetById(id));

            return new RedirectToPageResult("/Admin/ManageStaff");
        }
    }
}

MiraiAnimation/Pages/Admin/ManageUser.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MiraiAnimation.Model;
using MiraiAnimation.Model.Services;

namespace MiraiAnimation.Pages.Admin {
	[Authorize(Policy = "AdminRole")]
	public class ManageUserModel : PageModel {
        private readonly IDbService<User, string> _userCollection;

        public IEnumerable<User> Users { get; set; }

        [BindProperty]
        public User User { get; set; }
        public ManageUserModel(IDbService<User, string> userCollection) {
			_userCollection = userCollection;
        }

        public void OnGet() {
            Users = _userCollection.GetAll();
        }

        public IActionResult OnPostEdit() {
            if (!ModelState.IsValid) {
                Users = _userCollection.GetAll();
                return Page();
            }

            User _user = _userCollection.GetById(User.id.ToString());

            if(User.password != null) {
				PasswordHasher<User> hasher = new PasswordHasher<User>();

                User.password = hasher.HashPassword(User, User.password);
			} else {
                User.password = _user.password;

			}

            User.indirizzo.id = _user.indirizzo.id;
            User.verificato = _user.verificato;
            User.carrello = _user.carrello;
            User.ordini = _user.ordini;
            User.datiVerifica = _user.datiVerifica;

            _userCollection.EditElement(User);

            return new RedirectToPageResult("/Admin/ManageUser");
        }

        public IActionResult OnPostDelete(string id) {
            _userCollection.RemoveElement(_userCollection.GetById(id.ToString()));

			return new RedirectToPageResult("/Admin/ManageUser");
		}
    }
}

MiraiAnimation/Pages/Admin/ManageAnimation.cshtml
@page
@model MiraiAnimation.Pages.Admin.ManageAnimationModel
@section CSS {
	<link rel="stylesheet" href="/css/animManager.css" type="text/css">
}

@using MiraiAnimation.Model;

<div id="container" class="container pt-4 mt-4">
	<div class="accordion" id="accordionAnim">
		<div class="card bg-dark">
			<div class="card-header bg-light" id="headingEdit">
				<h2 class="mb-0">
					<button class="btn btn-light btn-block text-left" type="button" data-toggle="collapse" data-target="#edit" aria-expanded="true" aria-controls="edit">
						Modifica un'animazione
					</button>
				</h2>
			</div>

			<div id="edit" class="collapse show" aria-labelledby="headingEdit" data-parent="#accordionAnim">
				<div class="card-body bg-dark">
					<form id="animation" asp-page-handler="Edit" enctype="multipart/form-data" onsubmit="return checkInsertEditForm(this)">
						<span>Animazione:</span>
						<select name="codiceAnimazione" onchange="loadAnim()">
							<option value="" disabled selected>Seleziona un'opzione</option>
							@foreach(Animation anim in Model.Animations) {
								<option value="@anim.id">@anim.titolo</option>
							}
						</select>

						<div id="anim" class="pt-2">
							<input type="hidden" asp-for="Anim.id" value="">
							<label asp-for="Anim.titolo">Titolo:</label> 
							<input id="titoloEdit" type="text" asp-for="Anim.titolo" required> <br />
							<span class="error errorNome" asp-validation-for="Anim.titolo"></span><br />

							<label asp-for="Anim.genere">Genere: </label> 
							<input type="text" id="genereEdit" asp-for="Anim.genere" required> <br />
							<span class="error errorGenere" asp-validation-for="Anim.genere"></span><br />

							<span>Tipo:</span>
							<input type="radio" id="serieEdit" asp-for="Anim.tipo" value="serie" required> Serie
							<input type="radio" id="filmEdit" asp-for="Anim.tipo" value="film" required> Film <br />
							<span class="error errorUscita" asp-validation-for="Anim.tipo"></span>
							<br />

							<label asp-for="Anim.dataUscita">Data d'uscita:</label>
							<input type="text" id="dataEdit" asp-for="Anim.dataUscita"><br />
							<span class="error errorUscita" asp-validation-for="Anim.dataUscita"></span>
							<br />

							<label>Immagine: <input type="file" name="immagine"></label>
							<br />

							<input type="submit"> <br />
						</div>
						<p> </p>
					</form> <br />
				</div>
			</div>
		</div>

		<div class="card bg-dark">
			<div class="card-header bg-light" id="headingInsert">
				<h2 class="mb-0">
					<button class="btn btn-light btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#insert" aria-expanded="false" aria-controls="insert">
						Aggiungi un'animazione
					</button>
				</h2>
			</div>
			<div id="insert" class="collapse" aria-labelledby="headingInsert" data-parent="#accordionAnim">
				<div class="card-body bg-dark">
					<form id="addAnim" asp-page-handler="Add" enctype="multipart/form-data" onsubmit="return checkInsertEditForm(this)">
						<label asp-for="Anim.titolo">Titolo:</label>
						<input id="titoloAdd" type="text" asp-for="Anim.titolo" required> <br />
						<span class="error errorNome" asp-validation-for="Anim.titolo"></span><br />

						<label asp-for="Anim.genere">Genere: </label>
						<input type="text" id="genereAdd" asp-for="Anim.genere" required> <br />
						<span class="error errorGenere" asp-validation-for="Anim.genere"></span><br />

						<span>Tipo:</span>
						<input type="radio" id="serieAdd" asp-for="Anim.tipo" value="serie" required> Serie
						<input type="radio" id="filmAdd" asp-for="Anim.tipo" value="film" required> Film<br />
						<span class="error errorUscita" asp-validation-for="Anim.tipo"></span>
						<br />

						<label asp-for="Anim.dataUscita">Data d'uscita:</label>
						<input type="text" id="dataAdd" asp-for="Anim.dataUscita"><br />
						<span class="error errorUscita" asp-validation-for="Anim.dataUscita"></span>
						<br />

						<label>Immagine: <input type="file" name="immagine"></label>
						<br />

						<input type="submit"> <br />
						<p></p>
					</form>
				</div>
			</div>
		</div>
		<div class="card bg-dark">
			<div class="card-header bg-light" id="headingDelete">
				<h2 class="mb-0">
					<button class="btn btn-light btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#delete" aria-expanded="false" aria-controls="delete">
						Cancella un'animazione
					</button>
				</h2>
			</div>
			<div id="delete" class="collapse" aria-labelledby="headingDelete" data-parent="#accordionAnim">
				<div class="card-body bg-dark">
					<form name="del" asp-page-handler="Delete" method="post">
						<span>Animazione: </span>
						<select name="id">
							<option value="" disabled selected>Seleziona un'opzione</option>
							@foreach(Animation anim in Model.Animations) {
								<option value="@anim.id">@anim.titolo</option>
							}
						</select>
						<span class="error" id="errorDel"></span>
						<input class="ml-2" type="submit">
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts{
	<script src="/js/animManager.js"></script>
}

MiraiAnimation/Pages/Admin/ManageBluRay.cshtml
@page
@model MiraiAnimation.Pages.Admin.ManageBluRayModel
@section CSS{
    <link rel="stylesheet" href="/css/manageBluRay.css" type="text/css">
}

@using MiraiAnimation.Model;

<div id="container" class="container pt-4 mt-4">
    <div class="accordion" id="accordionBD">
        <!-- Edit -->
        <div class="card bg-dark">
            <div class="card-header bg-light" id="headingEdit">
                <h2 class="mb-0">
                    <button class="btn btn-light btn-block text-left" type="button" data-toggle="collapse" data-target="#edit" aria-expanded="true" aria-controls="edit">
                        Modifica un cofanetto
                    </button>
                </h2>
            </div>

            <div id="edit" class="collapse show" aria-labelledby="headingEdit" data-parent="#accordionBD">
                <div class="card-body bg-dark">
                    <form name="editBD" id="editBD" asp-page-handler="Edit" enctype="multipart/form-data" onsubmit="return checkForm(this)">
                        <span>Cofanetto: </span><select name="id" onchange="loadBD()">
                            <option value="" disabled selected>Selezione un'opzione</option>
                            @foreach (BluRay bd in Model.Bds) {
                                <option value="@bd.id">@bd.anim.titolo</option>
                            }
                        </select>

                        <div id="cofanetto">
                            <label asp-for="Bd.descrizione"> Descrizione: </label><br />
                            <textarea id="descrizioneEdit" asp-for="Bd.descrizione" rows="5" cols="30" maxlength="255" required></textarea>
                             <br />
                            <span class="error errorContenuto" asp-validation-for="Bd.descrizione"></span><br/>

                            <label asp-for="Bd.prezzo">Prezzo:</label>
                            <input id="prezzoEdit" type="number" class="numb" asp-for="Bd.prezzo" min="1" max="999" required> <br />
                            <span class="error errorPrezzo" asp-validation-for="Bd.prezzo"></span><br/>

                            <label>Immagine: <input type="file" name="immagine"></label> <br />
                            <input type="submit"> <br />
                        </div>
                        <span class="error"></span><br />
                    </form>
                </div>
            </div>
        </div>

        <!-- Add -->
        <div class="card bg-dark">
            <div class="card-header bg-light" id="headingInsert">
                <h2 class="mb-0">
                    <button class="btn btn-light btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#insert" aria-expanded="false" aria-controls="insert">
                        Inserisci un cofanetto
                    </button>
                </h2>
            </div>
            <div id="insert" class="collapse" aria-labelledby="headingInsert" data-parent="#accordionBD">
                <div class="card-body bg-dark">
                    <form id="insertBD" asp-page-handler="Add" enctype="multipart/form-data" onsubmit="return checkForm(this)">
                        Animazione: <select name="animazione">
                            <option value="" disabled selected>Selezione un'opzione</option>
                            @foreach (Animation anim in Model.Animations) {
                                <option value="@anim.id">@anim.titolo</option >
                            }
                        </select> <br />

                        <label asp-for="Bd.descrizione"> Descrizione: </label><br />
                        <textarea id="descrizioneEdit" asp-for="Bd.descrizione" rows="5" cols="30" maxlength="255" required></textarea>
                        <br />
                        <span class="error errorContenuto" asp-validation-for="Bd.descrizione"></span><br />

                        <label asp-for="Bd.prezzo">Prezzo:</label>
                        <input id="prezzoEdit" type="number" class="numb" asp-for="Bd.prezzo" min="1" max="999" required> <br />
                        <span class="error errorPrezzo" asp-validation-for="Bd.prezzo"></span><br />

                        <label>Immagine: <input type="file" name="immagine"></label> <br />

                        <input type="submit"> <br />
                        <span class="error"></span><br />
                    </form>
                </div>
            </div>
        </div>

        <!-- Delete -->
        <div class="card bg-dark">
            <div class="card-header bg-light" id="headingDelete">
                <h2 class="mb-0">
                    <button class="btn btn-light btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#delete" aria-expanded="false" aria-controls="delete">
                        Cancella un cofanetto
                    </button>
                </h2>
            </div>
            <div id="delete" class="collapse" aria-labelledby="headingDelete" data-parent="#accordionBD">
                <div class="card-body bg-dark">
                    <form id="bd" asp-page-handler="Delete">
                        <span>Cofanetto: </span>

                        <select name="id">
                            @foreach (BluRay bd in Model.Bds) {
                                <option value="@bd.id">@(bd.anim.titolo + " | "  + bd.prezzo)</option>
                            }
                        </select>

                        <input class="ml-2" type="submit"> <br />
                        <span></span><br />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="/js/manageBluRay.js"></script>
}

MiraiAnimation/Pages/Admin/ManageStaff.cshtml
@page
@model MiraiAnimation.Pages.Admin.ManageStaffModel
@section CSS{
    <link rel="stylesheet" href="/css/manageStaff.css" type="text/css">
}

@using MiraiAnimation.Model;

<div id="container" class="container pt-4 mt-4">
    <div class="accordion" id="accordionStaff">
        <!-- Edit -->
        <div class="card bg-dark">
            <div class="card-header bg-light" id="headingEdit">
                <h2 class="mb-0">
                    <button class="btn btn-light btn-block text-left" type="button" data-toggle="collapse" data-target="#edit" aria-expanded="true" aria-controls="edit">
                        Modifica un personale
                    </button>
                </h2>
            </div>

            <div id="edit" class="collapse show" aria-labelledby="headingEdit" data-parent="#accordionStaff">
                <div class="card-body bg-dark">
                    <form name="editStaff" id="editStaff" asp-page-handler="Edit" onsubmit="return checkEditForm()">

                        <span>Personale: </span>
                        <select name="id" onchange="loadStaff()">
                            <option value="" disabled selected>Seleziona un'opzione</option>
                            @foreach (Staff staff in Model.Staffs) {
                                <option value="@staff.id">@(staff.nome + " " + staff.cognome + " | " + staff.ruolo)</option>
                            } 
                        </select> <br />

                        <div class="py-2" id="staff">
                            <label asp-for="Staff.nome">Nome:</label> 
                            <input id="nomeEdit" type="text" asp-for="Staff.nome" required> <br />
                            <span class="error" asp-validation-for="Staff.nome"></span>

                            <label asp-for="Staff.cognome">Cognome:</label>
                            <input id="cognomeEdit" type="text" asp-for="Staff.cognome" required> <br />
                            <span class="error" asp-validation-for="Staff.nome"></span>

                            <label asp-for="Staff.anniServizio">Anni servizio:</label>
                            <input id="anniEdit" type="number" class="anni" asp-for="Staff.anniServizio" min="0" required></label> <br />
                            <span class="error" id="errorAnniEdit" asp-validation-for="Staff.anniServizio"></span>

                            Ruolo: 	<br />
                            <input id="direttoreEdit" type="radio" asp-for="Staff.ruolo" value="Direttore" required> Direttore <br />
                            <input id="tecnicoEdit" type="radio" asp-for="Staff.ruolo" value="Staff tecnico" required> Staff Tecnico <br />
                            <input id="registaEdit" type="radio" asp-for="Staff.ruolo" value="Regista" required> Regista <br />
                            <span class="error" id="errorRuoloEdit" asp-validation-for="Staff.ruolo"></span>

                            <input class="mt-2" type="submit"> <br />
                        </div>
                    </form>
                    <span class="error"></span><br />
                </div>
            </div>
        </div>

        <!-- Add -->
        <div class="card bg-dark">
            <div class="card-header bg-light" id="headingInsert">
                <h2 class="mb-0">
                    <button class="btn btn-light btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#insert" aria-expanded="false" aria-controls="insert">
                        Inserisci un personale
                    </button>
                </h2>
            </div>
            <div id="insert" class="collapse" aria-labelledby="headingInsert" data-parent="#accordionStaff">
                <div class="card-body bg-dark">
                    <form name="insertStaff" id="insertStaff" asp-page-handler="Add" onsubmit="return checkInsertForm()">

                        <label asp-for="Staff.nome">Nome:</label>
                        <input id="nomeAdd" type="text" asp-for="Staff.nome" required> <br />
                        <span class="error" asp-validation-for="Staff.nome"></span>

                        <label asp-for="Staff.cognome">Cognome:</label>
                        <input id="cognomeAdd" type="text" asp-for="Staff.cognome" required> <br />
                        <span class="error" asp-validation-for="Staff.nome"></span>

                        <label asp-for="Staff.anniServizio">Anni servizio:</label>
                        <input id="anniAdd" type="number" class="anni" asp-for="Staff.anniServizio" min="0" required></label> <br />
                        <span class="error" id="errorAnniAdd" asp-validation-for="Staff.anniServizio"></span>

                        Ruolo: 	<br />
                        <input id="direttoreAdd" type="radio" asp-for="Staff.ruolo" value="Direttore" required> Direttore <br />
                        <input id="tecnicoAdd" type="radio" asp-for="Staff.ruolo" value="Staff tecnico" required> Staff Tecnico <br />
                        <input id="registaAdd" type="radio" asp-for="Staff.ruolo" value="Regista" required> Regista <br />
                        <span class="error" id="errorRuoloAdd" asp-validation-for="Staff.ruolo"></span>

                        <input class="mt-2" type="submit"> <br />
                    </form>
                    <span class="error"></span><br />
                </div>
            </div>
        </div>

        <!-- Delete -->
        <div class="card bg-dark">
            <div class="card-header bg-light" id="headingDelete">
                <h2 class="mb-0">
                    <button class="btn btn-light btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#delete" aria-expanded="false" aria-controls="delete">
                        Cancella un membro del personale
                    </button>
                </h2>
            </div>
            <div id="delete" class="collapse" aria-labelledby="headingDelete" data-parent="#accordionStaff">
                <div class="card-body bg-dark">
                    <form id="deleteStaff" asp-page-handler="Delete">
                        <span>Personale: </span>
                        <select name="id">
                            @foreach (Staff staff in Model.Staffs) {
                                <option value="@staff.id"> @(staff.nome + " " + staff.cognome + " | " + staff.ruolo)</option>
                            }
                        </select>
                        <input class="ml-2" type="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="/js/manageStaff.js"></script>
}

MiraiAnimation/Pages/Admin/ManageUser.cshtml
@page
@model MiraiAnimation.Pages.Admin.ManageUserModel
@section CSS{
	<link rel="stylesheet" href="/css/manageUser.css" type="text/css">
}

@using MiraiAnimation.Model;

<div id="container" class="container pt-4 mt-4">
	<div class="accordion" id="accordionUser">
		<!-- Edit -->
		<div class="card bg-dark">
			<div class="card-header bg-light" id="headingEdit">
				<h2 class="mb-0">
					<button class="btn btn-light btn-block text-left" type="button" data-toggle="collapse" data-target="#edit" aria-expanded="true" aria-controls="edit">
						Modifica un utente
					</button>
				</h2>
			</div>

			<div id="edit" class="collapse show" aria-labelledby="headingEdit" data-parent="#accordionUser">
				<div class="card-body bg-dark">
					<form id="editForm" name="editForm" asp-page-handler="Edit" onsubmit="return checkEditForm()">
						<span>Utente: </span>
						<select name="id" onchange="loadUser()">
							<option value="" disabled selected>Seleziona un'opzione</option>
							@foreach (User user in Model.Users) {
								<option value="@user.id">@user.username</option>
							}
						</select>
						<span class="error" id="errorUserEdit"></span>

						<div class="py-2" id="userDiv">
							<label asp-for="User.username">Username:</label>
							<input type="text" asp-for="User.username"><br />
							<span class="error" asp-validation-for="User.username"></span><br/>

							<label asp-for="User.password">Password:</label> 
							<input type="password" asp-for="User.password"><br />
							<span class="error" asp-validation-for="User.password"></span>

							<label asp-for="User.email">E-mail:</label>
							<input type="text" asp-for="User.email"><br />
							<span class="error" asp-validation-for="User.email"></span><br/>

							<label asp-for="User.nome">Nome:</label>
							<input type="text" asp-for="User.nome"><br />
							<span class="error" asp-validation-for="User.nome"></span><br/>

							<label asp-for="User.cognome">Cognome:</label>
							<input type="text" asp-for="User.cognome"><br />
							<span class="error" asp-validation-for="User.cognome"></span><br />

							<label asp-for="User.dataNascita">Data di nascita:</label>
							<input type="text" asp-for="User.dataNascita"><br />
							<span class="error" asp-validation-for="User.dataNascita"></span><br />

							<label>Indirizzo:</label><br />
							<label asp-for="User.indirizzo.città">Città:</label>
							<input type="text" asp-for="User.indirizzo.città"><br />
							<span class="error" asp-validation-for="User.indirizzo.città"></span><br />

							<label asp-for="User.indirizzo.via">Via:</label>
							<input type="text" asp-for="User.indirizzo.via"><br />
							<span class="error" asp-validation-for="User.indirizzo.via"></span><br />

							<label asp-for="User.indirizzo.CAP">CAP:</label>
							<input type="text" asp-for="User.indirizzo.CAP"><br />
							<span class="error" asp-validation-for="User.indirizzo.CAP"></span><br />

							<span id="tipo" class="bold">Tipo:</span> <br />
							<input type="radio" asp-for="User.tipo" value="utente"> Utente <br />
							<input type="radio" asp-for="User.tipo" value="admin"> Amministratore <br />
							<span class="error" id="errorTipo" asp-validation-for="User.tipo"></span>


							<input type="submit" value="Conferma"> <br />
						</div>
					</form>
					<span class="error"></span><br />
				</div>
			</div>
		</div>

		<!-- Delete -->
		<div class="card bg-dark">
			<div class="card-header bg-light" id="headingDelete">
				<h2 class="mb-0">
					<button class="btn btn-light btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#delete" aria-expanded="false" aria-controls="delete">
						Cancella un utente
					</button>
				</h2>
			</div>
			<div id="delete" class="collapse" aria-labelledby="headingDelete" data-parent="#accordionUser">
				<div class="card-body bg-dark">
					<form id="deleteForm" name="deleteForm" asp-page-handler="Delete" onsubmit="return checkDelForm()">
						<select name="id">
							<option value="" disabled selected>Seleziona un'opzione</option>
							@foreach (User user in Model.Users) {
								<option value="@user.id">@user.username</option>
							}
						</select>
						<span class="error" id="errorDel"></span>
						<input type="submit" value="Conferma"> <br />
					</form>
					<span></span><br />
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<script src="/js/manageUser.js"></script>
}